name: Code Coverage [CodeCov]

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_dev.txt
          pip freeze
          pip check

      - name: Test with coverage
        run: |
          python -m coverage erase
          python -m coverage run -m pytest

      - name: Report coverage
        run: |
          python -m coverage report
          python -m coverage report --skip-covered --skip-empty --format=markdown >> $GITHUB_STEP_SUMMARY
