name: Formatting

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install black
        run: |
          python -m pip install $(grep black requirements_dev.txt | xargs)
          python -m pip install black[jupyter]

      - name: Format with black
        run: |
          python -m black . --diff --check
