name: LSE Scraper

on:
  schedule:
    - cron: "0 9 * * *" # every day at 09:00 UTC
  workflow_dispatch:

env:
  INPUT_FILE: "data/LSE_input.csv"
  OUTPUT_FILE: "output/lse_stocks.csv"
  ARTIFACT_NAME: "lse_stocks"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python -m app.run --input ${{ env.INPUT_FILE }} --output ${{ env.OUTPUT_FILE }}

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_FILE }}
